version: "3"
services:
  csharp_app:
    container_name: csharp_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      ConnectionStrings_DefaultConnection: "Host=db;Database=postgres;Username=postgres;Password=Ode2000#"
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESS_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgressql/data
volumes:
  pgdata: {}
